services:
  core-app:
    image: cpr.opendata.center/app-core:build
    environment:
      APP_NAME: testing-webapp-core-app
      APP_ENV: testing
      APP_DEBUG: true
      APP_URL: http://core-api
      DB_CONNECTION: mysql
      DB_HOST: core-db
      DB_DATABASE: app
      DB_PASSWORD: password
      DB_USERNAME: app
      BROADCAST_DRIVER: soketi
      CACHE_DRIVER: redis
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      REDIS_HOST: core-redis
      REDIS_PASSWORD: redispassword
      MAIL_MAILER: array
      MESSAGING_URL: http://core-httpbin/status/201
      MESSAGING_WPP_DEFAULT_GROUP: WPP_DEFAULT_GROUP
      MESSAGING_WPP_URGENT_GROUP: WPP_URGENT_GROUP
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ticket-attachments
      AWS_ENDPOINT: "http://core-minio:9000"
      AWS_URL: "http://core-minio:9000/ticket-attachments"
      AWS_USE_PATH_STYLE_ENDPOINT: true
      PUSHER_HOST: core-soketi
      PUSHER_APP_ID: app-id
      PUSHER_APP_KEY: app-key
      PUSHER_APP_SECRET: app-secret
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: "app-key"
      MIX_PUSHER_APP_CLUSTER: "app-key"
      GRAFANA_API_URL: https://grafana.opendata.center
      GRAFANA_API_KEY: e5604b1f-1d3b-4f0a-8d0b-b110af9af5f3
    networks:
      - testing-core-app
    volumes:
      - app-core-src:/usr/src/app
    depends_on:
      core-db:
        condition: service_healthy
      core-minio:
        condition: service_started
      core-redis:
        condition: service_started
      core-soketi:
        condition: service_started
  core-db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PASSWORD: password
      MARIADB_USER: app
      MARIADB_AUTO_UPGRADE: 1
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
    networks:
      - testing-core-app
  core-api:
    image: nginx:alpine
    networks:
      - testing-core-app
    volumes:
      - app-core-src:/usr/src/app:ro
      - ./nginx-app-core.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - core-app
  core-minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /tmp
    networks:
      - testing-core-app
  core-minio-create-buckets:
    image: minio/mc
    depends_on:
      core-minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://core-minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ticket-attachments;
      /usr/bin/mc mb myminio/contracts;
      /usr/bin/mc mb myminio/discovery;
      /usr/bin/mc mb myminio/proposals;
      /usr/bin/mc mb myminio/kb-articles;
      exit 0;
      "
    networks:
      - testing-core-app
  core-httpbin:
    image: kennethreitz/httpbin
    networks:
      - testing-core-app
  core-redis:
    image: redis:alpine
    restart: unless-stopped
    command: >
        --requirepass 'redispassword'
    networks:
      - testing-core-app
  core-soketi:
    image: 'quay.io/soketi/soketi:1.4-16-debian'
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: "-1"
      SOKETI_DEFAULT_APP_ID: app-id
      SOKETI_DEFAULT_APP_KEY: app-key
      SOKETI_DEFAULT_APP_SECRET: app-secret
      PUSHER_HOST: 127.0.0.1
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      METRICS_SERVER_PORT: 9601
      DEFAULT_APP_ENABLE_CLIENT_MESSAGES: false
    networks:
      - testing-core-app

networks:
  testing-core-app:

volumes:
  app-core-src:
