services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis

  queue-default:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: php artisan queue:work redis -n -vvv
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - ./api/.env
    depends_on:
      - app

  scheduler:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: php artisan schedule:work -n -vvv
    restart: unless-stopped
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - ./api/.env
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "4501:80"
    volumes:
      - ./api:/usr/src/app:ro
      - ./nginx-app.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - app

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis-data:/data

  mail:
    image: axllent/mailpit:v1.23
    ports:
      - "8025:8025"
      - "1025:1025"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - app

volumes:
  db-data:
  redis-data:
