services:
  core-app:
    image: cpr.opendata.center/app-core:develop
    environment:
      APP_NAME: testing-webapp-core-app
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://core-api
      DB_CONNECTION: mysql
      DB_HOST: core-db
      DB_DATABASE: app
      DB_PASSWORD: password
      DB_USERNAME: app
      BROADCAST_DRIVER: soketi
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MAIL_MAILER: log
      MESSAGING_URL: http://core-httpbin/status/201
      MESSAGING_WPP_DEFAULT_GROUP: WPP_DEFAULT_GROUP
      MESSAGING_WPP_URGENT_GROUP: WPP_URGENT_GROUP
      REDIS_HOST: core-redis
      REDIS_PASSWORD: password
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ticket-attachments
      AWS_ENDPOINT: "http://core-minio:9000"
      AWS_URL: "http://core-minio:9000/ticket-attachments"
      AWS_USE_PATH_STYLE_ENDPOINT: true
      PUSHER_HOST: core-soketi
      PUSHER_APP_ID: app-id
      PUSHER_APP_KEY: app-key
      PUSHER_APP_SECRET: app-secret
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY: "app-key"
      MIX_PUSHER_APP_CLUSTER: "app-key"
      GRAFANA_API_URL: https://grafana.opendata.center
      GRAFANA_API_KEY: e5604b1f-1d3b-4f0a-8d0b-b110af9af5f3
    volumes:
      - app-core-src:/usr/src/app
    depends_on:
      - core-db
      - core-redis
      - core-soketi
  core-db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PASSWORD: password
      MARIADB_USER: app
      MARIADB_AUTO_UPGRADE: 1
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
  core-api:
    image: nginx:alpine
    volumes:
      - app-core-src:/usr/src/app:ro
      - ./nginx-app-core.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - core-app
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 30s
      test:
          - CMD
          - curl
          - --fail
          - http://localhost/version
  core-minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /tmp
  core-httpbin:
    image: kennethreitz/httpbin
  core-soketi:
    image: 'quay.io/soketi/soketi:1.4-16-debian'
    restart: unless-stopped
    environment:
      SOKETI_DEBUG: "-1"
      SOKETI_DEFAULT_APP_ID: app-id
      SOKETI_DEFAULT_APP_KEY: app-key
      SOKETI_DEFAULT_APP_SECRET: app-secret
      PUSHER_HOST: 127.0.0.1
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      METRICS_SERVER_PORT: 9601
      DEFAULT_APP_ENABLE_CLIENT_MESSAGES: false
  core-redis:
    image: redis:alpine
    restart: unless-stopped
    command: >
        --requirepass password

  test:
    image: cpr.opendata.center/app-web-testing:main
    env_file: .env
    mem_limit: 8g
    memswap_limit: 8g
    environment:
      NODE_OPTIONS: "--max-old-space-size=8192"
    volumes:
      - ./:/usr/src/app

volumes:
  app-core-src:
