default:
    tags:
        - docker

image: mallardduck/gitlab-ci-pipeline-php:8.1

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

phpcpd:
  script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
    - php phpcpd.phar app/ --min-lines=50
  dependencies: []
  cache:
    paths:
      - phpcpd.phar
